<a href="https://colab.research.google.com/github/HimanshuRajput-0/Machine_Learning/blob/main/ML_by_FreeCodeCamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```Machine Learning is an area of computer science which focuses on algorithms which help a computer learn from data without explicit programming.```

```AI is an area of Computer Science which focuses on to enable computers and machines to perform human-like tasks and simulate human behavior.```

```Machine learning is a subset of AI that tries to solve a specific problem and make predictions using data.```

```Data Science is a field that attempts to find the pattern and draw insights from data.```

**All fields Overlaps and all use ML!**

```Types of Machine Learning: ```

1.   Supervised : uses labeled inputs to train models and learn outputs.
2.   Unsuperised : uses unlabeled data to learn about patterns in data.
3.   Reinforcement : agent learning in interactive environment based on rewards and penalties.

```For computer a picture is just some pixcels with colors.```

```Importing basic and necessary libraries:```

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

```Reading our csv file to see what is in it.```

In [ ]:
pd.read_csv("iris_synthetic_data.csv")

      sepal length  sepal width  petal length  petal width           label
0              5.2          3.8           1.5          0.3     Iris-setosa
1              5.3          4.1           1.5          0.1     Iris-setosa
2              4.8          3.1           1.5          0.2     Iris-setosa
3              5.2          3.7           1.5          0.2     Iris-setosa
4              4.9          3.0           1.5          0.3     Iris-setosa
...            ...          ...           ...          ...             ...
2995           7.2          3.6           6.0          2.5  Iris-virginica
2996           7.3          3.0           6.2          2.1  Iris-virginica
2997           6.9          3.2           5.7          2.3  Iris-virginica
2998           7.5          2.8           6.0          2.0  Iris-virginica
2999           6.7          3.0           5.3          2.3  Iris-virginica

[3000 rows x 5 columns]

```CSV = Comma Seperated Values```

```Saving our file data in a variable named df to perform operations in it.```

In [ ]:
df = pd.read_csv("iris_synthetic_data.csv")

```Using head function to display first 5 rows of the data.```

In [ ]:
df.head()

   sepal length  sepal width  petal length  petal width        label
0           5.2          3.8           1.5          0.3  Iris-setosa
1           5.3          4.1           1.5          0.1  Iris-setosa
2           4.8          3.1           1.5          0.2  Iris-setosa
3           5.2          3.7           1.5          0.2  Iris-setosa
4           4.9          3.0           1.5          0.3  Iris-setosa

```Getting information of the data```

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal length  3000 non-null   float64
 1   sepal width   3000 non-null   float64
 2   petal length  3000 non-null   float64
 3   petal width   3000 non-null   float64
 4   label         3000 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 117.3 KB

```Using unique function to see the number of unique values in the column.```

In [ ]:
df['label'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

```As we can see that there are multiple strings and our computer is not able to underestand them so we need to convert them into the integer.```

```There are two types of encoding strategy : for this conversion.```

```1. Label Encoding: if strings are in order or ranking they are assigned with sequential numbers from 0 to n-1.```

```Ex: 0 = Iris-setosa, 1 = Iris-versicolor, 2 = Iris-virginica.```

```Best use for tree-based machine learning algorithms like Random Forest, Decision Trees, or XGBoost which handel sequential number well.```

```2. One Hot Encoding: if strings have no logical order, then assigning sequential integers can mislead the model. Instead, the column is split into multiple separate columns and only assign 0 and 1.```

```Ex: This converts the single column into three separate columns. Each column only contains a 0 (absent) or 1(present).```

```like: [1,0,0] = Iris-setosa, [0,1,0] = Iris versicolor, [0,0,1] = Iris-virginica.```

```Best used for Distance based algorithms like Logistic Regression, SVM, Neural Networks.```

**```We can perform the similar task using mapping.```**

In [ ]:
mapping = {'Iris-setosa' : 0, 'Iris-versicolor' : 1, 'Iris-virginica' : 2}

In [ ]:
df['label'] = df['label'].map(mapping)

In [ ]:
df.head()

   sepal length  sepal width  petal length  petal width  label
0           5.2          3.8           1.5          0.3      0
1           5.3          4.1           1.5          0.1      0
2           4.8          3.1           1.5          0.2      0
3           5.2          3.7           1.5          0.2      0
4           4.9          3.0           1.5          0.3      0

```Features : are the columns which we are gng to pass to the model to help us predict the label.```

```So our features here are: Sepal Length, Sepal Width, Petal Length, Petal width.```

```Rows are like samples.```

```The idea of predcting the labels of the future samples comes under classification.```

**Classification is a supervised learning technique used to predict discrete caegories or class label for the input data.**